#ifndef COMMON_HLSL
#define COMMON_HLSL

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

inline float TimeLoop01()
{
    // _SinTime is still available in URP
    return _SinTime.w * 0.5 + 0.5;
}

inline float MainLightOnSurface(float3 normalOS)
{
    float3 worldNormal = TransformObjectToWorldNormal(normalOS);
    Light mainLight = GetMainLight();
    return dot(normalize(worldNormal), mainLight.direction);
}



inline float Fresnel(float3 worldNormal, float3 viewDir, float power)
{
    return pow(1.0 - saturate(dot(normalize(worldNormal), normalize(viewDir))), power);
}

inline float pulse(float a, float b, float x)
{
    return step(a, x) - step(b, x);
}

inline float smoothpulse(float a1, float a2, float b1, float b2, float x)
{
    return smoothstep(a1, a2, x) - smoothstep(b1, b2, x);
}



// DevNote: Remap is generated by unity
inline float Remap2(float value, float fromMin, float fromMax, float toMin, float toMax)
{
    // newValue = [new range] * [value in percentage based on old range]
    // 1. calculate old range  
    // 2. calculate value in terms of percentage based on old range
    // 3. calculate newValue using percentage on new range
    
    return toMin + (toMax - toMin) * ((value - fromMin) / (fromMax - fromMin));
}
inline float RemapClamped(float value, float fromMin, float fromMax, float toMin, float toMax)
{
    float t = saturate((value - fromMin) / (fromMax - fromMin));
    return lerp(toMin, toMax, t);
}
inline float Remap1101(float num)
{
    return num * 0.5 + 0.5;
}

#endif // COMMON_HLSL